/** Dashboard copy. Spanish ships as the only dictionary; the shape keeps translation mechanical. */
export const copy = {
  title: 'Uso de modelos',
  eyebrow: 'Estadísticas del perfil',
  subtitle: 'Actividad y consumo de todas tus conversaciones, por modelo y proveedor.',
  sidebar: 'Uso de modelos',
  back: 'Volver a la conversación',
  refresh: 'Actualizar',
  refreshing: 'Actualizando…',
  metricLabel: 'Métrica',
  metric: { tokens: 'Tokens', requests: 'Peticiones' },
  filters: { label: 'Filtrar por modelo o proveedor', search: 'Filtrar por modelo o proveedor…', clear: 'Limpiar filtro', empty: 'Ningún modelo coincide con el filtro.' },
  legend: { less: 'Menos', more: 'Más' },
  loading: 'Analizando sesiones…',
  empty: 'Sin actividad en el rango seleccionado.',
  failed: 'No se pudo leer el uso. Vuelve a intentarlo.',
  retry: 'Reintentar',
  kpi: {
    tokens: 'Tokens totales',
    requests: 'Peticiones',
    peak: 'Pico diario',
    activeDays: 'Días activos',
  },
  updated: 'Actualizado',
  scanned: 'sesiones analizadas',
  zoneFallback: 'La zona del navegador no es válida; los días se muestran en la zona del Host',
  overview: {
    title: 'Últimos 12 meses',
    rail: 'Modelos más usados',
    railHint: 'Consumo del período',
    activeDaysHint: (active: number, total: number) => `${active} de ${total} días con actividad`,
    others: (models: number) => `Otros ${models} ${models === 1 ? 'modelo' : 'modelos'}`,
    historyHint: 'Total histórico del perfil, sin filtros',
  },
  breakdown: {
    title: 'Desglose por proveedor',
    hint: 'Cada proveedor agrupa sus modelos; despliégalo para ver el detalle.',
    hintRequests: 'Participación en peticiones durante el período seleccionado.',
    hintTokens: 'Participación en tokens durante el período seleccionado.',
    models: (count: number) => `${count} ${count === 1 ? 'modelo' : 'modelos'}`,
    expand: 'Desplegar modelos',
    collapse: 'Plegar modelos',
    /** Both cache halves are one column; the cell title spells them out from the exact counts. */
    cacheTitle: (read: string, write: string) => `Lectura ${read} · Escritura ${write}`,
    columns: {
      group: 'Proveedor / modelo',
      tokens: 'Tokens',
      share: 'Participación',
      requests: 'Peticiones',
      input: 'Entrada no cacheada',
      output: 'Salida',
      cache: 'Caché',
      last: 'Último uso',
    },
  },
  footnote: { zone: 'Zona horaria', noCost: 'Sin estimaciones de coste' },
} as const;
