/** Dashboard copy. English ships as the only dictionary; the shape keeps translation mechanical. */
export const copy = {
  title: 'Model usage',
  eyebrow: 'Profile statistics',
  subtitle: 'Activity and consumption across all your conversations, by model and provider.',
  sidebar: 'Model usage',
  back: 'Back to conversation',
  refresh: 'Refresh',
  refreshing: 'Refreshing…',
  metricLabel: 'Metric',
  metric: { tokens: 'Tokens', requests: 'Requests' },
  filters: { label: 'Filter by model or provider', search: 'Filter by model or provider…', clear: 'Clear filter', empty: 'No model matches the filter.' },
  legend: { less: 'Less', more: 'More' },
  loading: 'Analyzing sessions…',
  empty: 'No activity in the selected range.',
  failed: 'Usage could not be read. Try again.',
  retry: 'Retry',
  kpi: {
    tokens: 'Total tokens',
    requests: 'Requests',
    peak: 'Daily peak',
    activeDays: 'Active days',
  },
  updated: 'Updated',
  scanned: 'sessions analyzed',
  zoneFallback: 'The browser time zone is invalid; days are shown in the Host time zone',
  overview: {
    title: 'Last 12 months',
    rail: 'Most used models',
    railHint: 'Consumption over the period',
    activeDaysHint: (active: number, total: number) => `${active} of ${total} days with activity`,
    others: (models: number) => `Others ${models} ${models === 1 ? 'model' : 'models'}`,
    historyHint: 'Profile lifetime total, unfiltered',
  },
  breakdown: {
    title: 'Breakdown by provider',
    hint: 'Each provider groups its models; expand it to see the detail.',
    hintRequests: 'Share of requests over the selected period.',
    hintTokens: 'Share of tokens over the selected period.',
    models: (count: number) => `${count} ${count === 1 ? 'model' : 'models'}`,
    expand: 'Expand models',
    collapse: 'Collapse models',
    /** Both cache halves are one column; the cell title spells them out from the exact counts. */
    cacheTitle: (read: string, write: string) => `Read ${read} · Write ${write}`,
    columns: {
      group: 'Provider / model',
      tokens: 'Tokens',
      share: 'Share',
      requests: 'Requests',
      input: 'Uncached input',
      output: 'Output',
      cache: 'Cache',
      last: 'Last used',
    },
  },
  footnote: { zone: 'Time zone', noCost: 'No cost estimates' },
} as const;
